#!/bin/sh

module="chardev.ko"
device="chardev"
group="root"
mode="664"

# invoke insmode with all arguments we got
/sbin/insmod -f $module || exit 1

major=`cat /proc/devices | awk "\\$2==\"$device\" {print \\$1}"`

echo "Major number = $major"

rm -f /dev/${device}
mknod /dev/${device} c $major 0

chgrp $group /dev/${device}
chmod $mode /dev/${device}

